--INNER JOIN
SELECT * FROM MEMBER;
SELECT * FROM NOTICE;

SELECT * FROM MEMBER 
INNER JOIN NOTICE 
ON MEMBER.ID=NOTICE.WRITER_ID;

SELECT * FROM NOTICE N JOIN MEMBER M
ON N.WRITER_ID=M.ID;

--OUTER JOIN
SELECT * FROM NOTICE N LEFT OUTER JOIN MEMBER M
ON N.WRITER_ID=M.ID;

--MEMBER 테이블 컬럼 이름 수정
ALTER TABLE MEMBER RENAME COLUMN JOINDATE TO REGDATE;

--ID, NAME 그리고 회원별 작성한 게시글 수를 조회하시오.
SELECT M.ID, M.NAME, COUNT(N.ID)
FROM MEMBER M LEFT OUTER JOIN NOTICE N
ON N.WRITER_ID=M.ID
GROUP BY M.ID, M.NAME;

--SELF JOIN
SELECT M.*, B.NAME BOSS_NAME FROM 
MEMBER M LEFT OUTER JOIN MEMBER B
ON B.ID=M.BOSS_ID;

--OLD JOIN
SELECT N.*, M.NAME WRITER_NAME 
FROM NOTICE N JOIN MEMBER M 
ON M.ID = N.WRITER_ID;

SELECT N.*, M.NAME WRITER_NAME 
FROM NOTICE N, MEMBER M  
WHERE M.ID = N.WRITER_ID;

--CROSS JOIN
SELECT N.*, M.NAME WRITER_NAME
FROM NOTICE N, MEMBER M;

--UNION : JOIN으로 합치는 방법
SELECT ID, NAME FROM MEMBER
    INTERSECT
SELECT WRITER_ID, TITLE FROM NOTICE;

SELECT ID, NAME FROM MEMBER WHERE ID LIKE '%n%'
    UNION
SELECT ID, NAME FROM MEMBER WHERE ID LIKE '%i%';

--VIEW
CREATE VIEW NOTICEVIEW
AS
SELECT N.ID, N.TITLE, N.WRITER_ID, M.NAME WRITER_NAME, COUNT(C.ID) COMMENT_CNT FROM MEMBER M
RIGHT OUTER JOIN NOTICE N ON M.ID = N.WRITER_ID
LEFT OUTER JOIN "COMMENT" C ON N.ID = C. NOTICE_ID
GROUP BY N.ID, N.TITLE, N.WRITER_ID, M.NAME;

SELECT * FROM NOTICEVIEW;

--데이터 딕셔너리
SELECT * FROM DICT;
SELECT * FROM USER_TABLES;

--INSERT NOTICE
INSERT INTO notice (
    id,
    title,
    writer_id,
    content,
    files
) VALUES (
    8,
    '50번째 게시글',
    'newlec',
    '하하호호호',
    '무언가'
);

SELECT * FROM NOTICE ORDER BY REGDATE DESC;